# Generated by Django 2.2.13 on 2022-01-23 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20220123_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='eye_color',
            field=models.CharField(blank=True, choices=[('black', 'BLACK'), ('white', 'WHITE'), ('green', 'GREEN'), ('blue', 'BLUE'), ('brown', 'BROWN'), ('yellow', 'YELLOW'), ('red', 'RED'), ('unknown', 'UNKNOWN'), ('purple', 'PURPLE')], max_length=32),
        ),
        migrations.AlterField(
            model_name='people',
            name='hair_color',
            field=models.CharField(blank=True, choices=[('black', 'BLACK'), ('white', 'WHITE'), ('blonde', 'BLONDE'), ('brown', 'BROWN'), ('none', 'NONE'), ('bald', 'BALD'), ('red', 'RED')], max_length=32),
        ),
    ]
